### ISSUE TITLE
Expose DockerCredsHelper APIs through auth

### ISSUE THREAD

**Issue by booninite** [google/nodejs-container-image-builder#16]
This is an awesome library and would enable an array of use cases for us.  I had one issue though, and that is getting it to properly authenticate to us.icr.io, the IBM Container Registry.

I noticed there is a DockerCredsHelper which provides functions for reading the config file and a function for providing registry configuration objects directly.  I've done this previously when building images programmatically using projects like https://www.npmjs.com/package/node-docker-api and it worked well.  If I could do something similar with this package, it would enable my eager adoption.

Thoughts on this type of change?  I'm happy to submit a PR to iterate over when I have spare time if you're open to it.

**Comment by soldair** [comment]
I would love for this to work with the ibm registry. Thanks for the issue!
I'm guessing you crash right around here https://github.com/google/nodejs-container-image-builder/blob/master/src/credentials-helper.ts#L41

So. by default if the container-image-builder doesn't find a credentials class for your registry it shells out to an installed docker credentials helper on the system. The same way the docker cli authenticates with a registry.  This means that by default if the docker cli can access the ibm registry the image builder should be able to also. It would be great to support the different configuration schemes that distinguish which credentials to use with which registry url if docker supports them. I'm cusious how you configure your own setup.

The Image class should also be able to pass options down directly into the authentication class. 
this seems to be a big oversight on my part. it should at least accept 
```
auth:{"docker registry host name".{Username:"",Secret:"",token:""}
```
and use the auth provided instead of trying to auth again.

For docker hub and gcr.io we added custom helpers because they authenticate differently than the OCI spec and it can be more efficient. If this is needed for ibm we'ed be happy to accept an authentication helper.

I would love more information on what you think we should do and i think we're very interested this contribution.

**Comment by soldair** [comment]
hey @booninite im curious if you would be willing to give master a try.
you can add 
```
"container-image-builder:"google/nodejs-container-image-builder"
```
as a dependency in your package.json to try out this version that's not released.

you can pass an auth token for your ibm registry to the image constructor like the updated example.
https://github.com/google/nodejs-container-image-builder#example

and you can find out more of the details here.
https://github.com/google/nodejs-container-image-builder#docker-registry-auth

```
const image = new Image('node:lts-slim','us.icr.io/my-project/my-image',{
    'us.icr.io':{
        token:"xxxxxxxxxxx"
    }
})
await image.addFiles({"/code":"./"))
image.save()
```
this code should use the token provided by you for us.icr.io
it should copy all of the layers for  `docker.io/node:lts-slim` to `us.icr.io/my-project`
add all the files in `./` to `/code` in `us.icr.io/my-project/my-image`

**Comment by amv93** [comment]
Hi @soldair ,
My application copies image from a gcr repository in project A to a gcr repository in project B.
Before copying to another project, I tried to copy to different repository in the same project.
I first do OAuth SSO login,get a token and then send the access token to the image constructor as follows:
```
var imgBuilder = require('container-image-builder');
const image = new imgBuilder.Image('gcr.io/myProj/test123/hello-world',
                         'gcr.io/myProj/demo/hello-world', 
                          {'  
                           gcr.io':{
                                token:tokens.access_token
                             }
                         })
```
But it crashes around here https://github.com/google/nodejs-container-image-builder/blob/master/src/credentials-helper.ts#L41
I have included the following line in package.json
`"container-image-builder": "github:google/nodejs-container-image-builder"`
 What am I missing here?

**Comment by soldair** [comment]
hi @amv93 you're running into a different issue. We should absolutely support passing in only token

you're using gcr and authentication to gcr is done with the google-auth-client npm package. the options you can pass are defined here: https://github.com/googleapis/google-auth-library-nodejs/blob/master/src/auth/googleauth.ts#L64

you can install the gcloud docker credentials helper https://cloud.google.com/container-registry/docs/advanced-authentication

Or you can defined an environment variable GOOGLE_APPLICATION_CREDENTIALS=/path/to/key.json.
Using the default auth means that in environments like cloud build etc you wont have to provide anything and the auth library will pull from the environment.

Lastly you should use the version on npm instead of this library as a github dependency.
